# Generated by Django 4.0.5 on 2022-11-01 09:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_userscenario_question_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scenarioconfig',
            name='done_tasks_familiarity_factor',
        ),
        migrations.RemoveField(
            model_name='scenarioconfig',
            name='error_completion_coefficient',
        ),
        migrations.RemoveField(
            model_name='scenarioconfig',
            name='stress_error_optimum',
        ),
        migrations.RemoveField(
            model_name='scenarioconfig',
            name='task_completion_coefficient',
        ),
        migrations.AlterField(
            model_name='skilltype',
            name='cost_per_day',
            field=models.FloatField(default=100, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='skilltype',
            name='development_quality',
            field=models.PositiveSmallIntegerField(default=100, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='skilltype',
            name='error_rate',
            field=models.FloatField(default=0.05, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AlterField(
            model_name='skilltype',
            name='management_quality',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='skilltype',
            name='signing_bonus',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='skilltype',
            name='throughput',
            field=models.FloatField(default=1, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
