# Generated by Django 4.1.4 on 2023-01-05 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_remove_scenarioconfig_done_tasks_familiarity_factor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatescenario',
            name='studio_template_id',
            field=models.TextField(default=''),
        ),
    ]
