# Generated by Django 4.1.4 on 2023-01-26 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_templatescenario_studio_template_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulationend',
            name='limit',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='simulationend',
            name='limit_type',
            field=models.TextField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='simulationend',
            name='type',
            field=models.TextField(blank=True, max_length=16),
        ),
    ]
